version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: lms-db
    environment:
      POSTGRES_DB: lms_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"   # dışarıdan erişmek istersen
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d lms_db"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lms-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      # application.properties içindeki placeholder'ları dolduruyoruz:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: lms_db
      DB_USER: postgres
      DB_PASSWORD: 1234

      # JWT'yi prod'da gizli ENV ile değiştir:
      JWT_SECRET: 1f4a7b9c2d3e4f60718293a4b5c6d7e81f4a7b9c2d3e4f60718293a4b5c6d7e8

      # (opsiyonel) JVM ayarları
      JAVA_OPTS: "-Xms256m -Xmx512m"
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  db_data:
